### ISSUE TITLE
ModuleNotFoundError: No module named 'slither.__main__'

### ISSUE THREAD

**Issue by morphean-sec** [crytic/slither#1036]
Hello there! Every time I try to run Slither on a directory, I receive the following issue which I'm not sure how to resolve.

```
~$: slither .

pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 5, in <module>
    from slither.__main__ import main
ModuleNotFoundError: No module named 'slither.__main__'
```

**Comment by 0xalpharush** [comment]
Did you clone the repo and build locally or install with pip? This looks like an issue with your python path at a glance.

**Comment by morphean-sec** [comment]
I installed it with pip.

**Comment by morphean-sec** [comment]
> Did you clone the repo and build locally or install with pip? This looks like an issue with your python path at a glance.

Yes, I installed the tool with pip. Specifically, `pip3 install slither-analyzer`

**Comment by 0xalpharush** [comment]
Can you try running `$(which slither)` and lmk what the output is?

**Comment by morphean-sec** [comment]
Here's the output.
```
:~$ (which slither)
/usr/local/bin/slither
```

**Comment by morphean-sec** [comment]
> Can you run `./usr/local/bin/slither`?

Hello gain Sers. Been a busy week, sorry. These instructions are unclear so this is what I run. Last I checked, pasting a file path into a terminal isn't a command. 😅
```
~$ ./usr/local/bin/slither
bash: ./usr/local/bin/slither: No such file or directory
```

**Comment by elopez** [comment]
Hi @morphean-sec - for completeness, which platform/operating system are you working on, and how did you install Python on it? Your first message makes me think there is something odd going on with your python installation - mainly due to this message in the error you posted:

```
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
```

If you have the time I would suggest starting from scratch - remove all python installations (pygame or otherwise), install the latest python from the system package manager, brew, or the official installer, and try installing slither again.

Alternatively, consider creating a `venv` and install slither inside of it, it should help remove any possible clashes you may have with other python things on your system: https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment
