### ISSUE TITLE
[Bug-Candidate]: False positive on "Contract locking ether found"

### ISSUE THREAD

**Issue by liron-navon** [crytic/slither#1145]
### Describe the issue:

The right way to transfer funds at the moment based on consensus is to use "call", yet "call" isn't supported by the [contracts-that-lock-ether](https://github.com/crytic/slither/wiki/Detector-Documentation#contracts-that-lock-ether)| detector, so it counts my contract as locking ether even if it doesn't... 

why I use call:
[stop-using-soliditys-transfer-now](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/)

### Code example to reproduce the issue:

```solidity

contract WithdrawMock {

    // solhint-disable-next-line no-empty-blocks
    function giveFunds() public payable {
        // just a function to recieve funds
    }

    function withdraw(address payable to, uint256 amount) public {
        (bool success, ) = to.call{value: amount}("");        
        require(success, "failed withdraw");
    }
}


```

### Version:

whatever is used in slither action, it says "slither-analyzer-0.8.2"

https://github.com/marketplace/actions/slither-action

**Comment by liron-navon** [comment]
up?

**Comment by 0xalpharush** [comment]
I cannot replicate this and call is considered in the detector https://github.com/crytic/slither/blob/e3b75c003eccbacd5577278dfe2c92752a187b94/slither/detectors/attributes/locked_ether.py#L60

Also, I think that blog is misleading and may introduce vulnerabilities that are not otherwise possible. see https://twitter.com/Mudit__Gupta/status/1509965799314042882?s=20&t=BvwLXFQ9tKdvwqd1GihVUg
