### ISSUE TITLE
Improvements on solc-version detectors

### ISSUE THREAD

**Issue by montyly** [crytic/slither#189]
The allowed version is out of date:
https://github.com/crytic/slither/blob/0891f9a8a5e5e096084476e4b2bd292c3685f251/slither/detectors/attributes/incorrect_solc.py#L39

Due to the frequent solc release, we might want to change the logic to allow future releases.

Additionally:
- 0.5.5 should not be used: https://twitter.com/ethchris/status/1105903546602528768
- the wiki link is incorrect

**Comment by rajeevgopalakrishna** [comment]
(There appears to be roughly one release per month https://github.com/ethereum/solidity/releases)

The options I see are:
1. Dynamically check released versions from Solidity github. While future proof, we might want to disallow any released versions that are later found to have bugs (e.g. 0.5.5) or deprecated.
2. Specify allowed versions in a config file which gets updated periodically instead of the detector code.
3. Allow user to specify/override allowed versions via CLI option.
4. Retain current logic and update allowed versions in detector code periodically.
5. ?

Any preferences?

**Comment by montyly** [comment]
Done with #240
It's a temporary solution, we will adjust the heuristic according to the frequency of the Solidity releases in the future
