### ISSUE TITLE
Can I debug the Slither by PyCharm?

### ISSUE THREAD

**Issue by jazefe** [crytic/slither#195]
I want to learn the analytical steps of Slither. And how do I run Slither with PyCharm?
Thanks.

**Comment by disconnect3d** [comment]
> And how do I run Slither with PyCharm?
The same way as any other Python script.

1. Clone slither repo `git clone https://github.com/crytic/slither.git`
2. In PyCharm `File -> Open...` - open slither repo/project
3. Highly recommended but not needed: [create a Python virtual environment](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html)
4. Run setup task `develop` to install the package in development mode along with installing its dependencies. To do it hit `Tools` menu in PyCharm and choose: <img src="https://user-images.githubusercontent.com/10009354/55521992-695e4100-5683-11e9-964e-ce1d7b097fec.png" width="250">
5. Hit the `Add configuration` button in PyCharm - this should be on the toolbar.
6. Hit the "+" button -> choose Python
7. Fill in things as in the screen - note that I chose `Module name`instead of `Script path`:
![image](https://user-images.githubusercontent.com/10009354/55522247-61eb6780-5684-11e9-9308-7933c2727c3e.png)

After those steps you should be able to run/debug slither on a given solidity file. The solidity file path should be specified in `Parameters` along with other arguments to slither.

Also don't forget that slither requires solc under the hood. If you are familiar with Docker, you might be interested with https://github.com/crytic/solc-select

**Comment by jazefe** [comment]
Thank you for your help, but I can't run the results on Mac OS. I can do it on Ubuntu 18.04. Is it not supported by Mac OS?
![image](https://user-images.githubusercontent.com/12013893/55524022-3c7b4f80-56be-11e9-85eb-316e1b6b0ea6.png)

**Comment by montyly** [comment]
Hi @jazefe ,
What version of solc are you using (`solc --version`) ? Can you share `reentrancy.sol`?

**Comment by jazefe** [comment]
@montyly 
The version is 0.6.1.

`pragma solidity ^0.4.24;

contract EtherBankStore {

    uint256 public withdrawalLimit = 1 ether;
    mapping(address => uint256) public lastWithdrawTime;
    mapping(address => uint256) public balances;

    function depositFunds() public payable {
        balances[msg.sender] += msg.value;
    }
    function withdrawFunds (uint256 _weiToWithdraw) public {
        require(balances[msg.sender] >= _weiToWithdraw);
        // limit_money
        require(_weiToWithdraw <= withdrawalLimit);
        // limit_time
        require(now >= lastWithdrawTime[msg.sender] + 1 weeks);
        require(msg.sender.call.value(_weiToWithdraw)());
        balances[msg.sender] -= _weiToWithdraw;
        lastWithdrawTime[msg.sender] = now;
    }
 }`

I can get the results on Ubuntu 18.04.

**Comment by montyly** [comment]
@jazefe: I am not aware of a 0.6.1 solc release, but your issue might come from `pragma solidity ^0.4.24;`. Could you remove the pragma and try again?

**Comment by jazefe** [comment]
I believe this problem is caused by solc. The 0.4.24 version of solc was not installed successfully on my Mac. When I chose to install the 0.4.24 solc by source, I could not install it successfully, but I successfully installed it above 0.5 by Homebrew.
So I gave up building on the Mac.

Ubuntu is better.
Thanks.
