### ISSUE TITLE
[Bug-Candidate]: false positive for unused-return

### ISSUE THREAD

**Issue by varunsrin** [crytic/slither#2021]
### Describe the issue:

`unused-return` check produces false positives even when the return values are used 

### Code example to reproduce the issue:

Issue can be reproduced by running `slither .` against [this commit](https://github.com/farcasterxyz/contracts/tree/ec667137456becafe2bb04b57f0f82e82244b67c)

Example of code that causes the issue is: 

```solidity
    function _sendNative(address to, uint256 amount) internal {
        if (address(this).balance < amount) revert InsufficientFunds();
        (bool success,) = payable(to).call{value: amount}("");
        if (!success) revert CallFailed();
    }
```

### Version:

0.9.5

### Relevant log output:

```shell
Bundler._sendNative(address,uint256) (src/Bundler.sol#123-127) ignores return value by (success) = address(to).call{value: amount}() (src/Bundler.sol#125)
StorageRent._sendNative(address,uint256) (src/StorageRent.sol#625-629) ignores return value by (success) = address(to).call{value: amount}() (src/StorageRent.sol#627)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#unchecked-low-level-calls


StorageRent._refreshPrice() (src/StorageRent.sol#435-470) ignores return value by (priceRoundId,answer,priceUpdatedAt,priceAnsweredInRound) = priceFeed.latestRoundData() (src/StorageRent.sol#453-454)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#unused-return
```
```

**Comment by horsefacts** [comment]
This isn't exactly a false positive, since we _are_ ignoring a returned value in both these cases. 

Our `_sendNative` is basically the same as OZ [`sendValue`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e50c24f5839db17f46991478384bfda14acfb830/contracts/utils/Address.sol#L64), but we _are_ ignoring the returndata. 

We're not using the value of `startedAt` returned by the price feed, which isn't usually used in ETH price feed validations. For the ETH price feed, I believe this is always equal to `updatedAt`. I would be OK adding an explanatory comment for each of these and a `// slither-disable-next-line` if you are.
