### ISSUE TITLE
[Bug-Candidate]: `filter_paths` doesn't work with `test` folder in `0.9.6` 

### ISSUE THREAD

**Issue by Pet3ris** [crytic/slither#2062]
### Describe the issue:

I recently tried to use filter paths on a private Foundry repository (that compiles successfully) to filter out `test` folder.

The run failed due to issues that were coming from the test files.

The repository runs without any issues with `solstat`, `pyrometer` and `solhint`.

I've mentioned this to your team but creating a tracking issue here just in case.

### Code example to reproduce the issue:

```
slither . --filter-paths "test"
```

### Version:

0.9.6

**Comment by smonicas** [comment]
Is the issue that `filter_paths` doesn't filter the results correctly or that slither crashes due to errors in tests and you would expect that by filtering them out slither should work? If the latter slither filters after running detectors/the core operations so that's why it would still fail, you can use this command to not compile scripts and tests in foundry so slither doesn't see them `forge build --build-info --skip '*/test/**' --skip '*/script/**' --force && slither . --ignore-compile` in the future it should be done automatically by slither.

**Comment by Pet3ris** [comment]
Thanks @smonicas!

This reveals another error but definitely fixes this issue. Thanks a lot :).

Feel free to close!

**Comment by smonicas** [comment]
If the new issue is an assertion error and you have the small snippet of code that should cause it you can open a new issue and maybe we can help even without the full codebase. Otherwise you can look in the open issues about assertion error and see if it's failing at the same point.

**Comment by smonicas** [comment]
I close this but leave a reference at #2026
