### ISSUE TITLE
[False-Positive]: ERC-4626 Conformance emitting events falsely flagging as failed

### ISSUE THREAD

**Issue by vikramarun** [crytic/slither#2109]
### Describe the false alarm that Slither raise and how you know it's inaccurate:

Slither claims that the required `Deposit` and `Withdraw` events as specified in the ERC-4626 spec (https://eips.ethereum.org/EIPS/eip-4626) are not emitted properly, but they are in multiple contracts

### Frequency

Occasionally

### Code example to reproduce the issue:

Example contracts that emit these events but fail the tests:

- slither-check-erc mainet:0x78bB3aEC3d855431bd9289fD98dA13F9ebB7ef15 FraxlendPair --erc erc4626

- slither-check-erc mainet:0x172455d14d1eb242e6f7f3b451529ab289095bb6 VaultDummyImplementation --erc erc4626

The second contract is the implementation contract for Instadapp's ETH v2 Vault here: https://etherscan.io/address/0xA0D3707c569ff8C87FA923d3823eC5D81c98Be78#code

### Version:

0.9.6

**Comment by smonicas** [comment]
The first case is reported because it checks the arguments type are the expected ones, however in this case they are `uint128` while the expected is `uint256` (`_amount`/`_shares` for Deposit and `_amountToReturn`/`_shares` for Withdraw). Maybe we should improve this case by checking if the argument type can be implicitly casted to the expected.
https://github.com/crytic/slither/blob/e5f2a86f0906fd62c6c4eccb9dbfa5ab30671a78/slither/tools/erc_conformance/erc/ercs.py#L133-L137
The second to me it seems a dummy implementation which does not actually implement the functions i.e. the events are not emitted.

**Comment by vikramarun** [comment]
Got it on the first case, thanks. That would be a nice comparison. 

For the second case, curious if there is any suggested behavior to look at proxied contracts in general when using the conformance tool? Querying the proxy wouldn't return anything sensical and typically querying the implementation contract is fine. A proxied vault where querying the implementation passed for reference: https://optimistic.etherscan.io/address/0x81C9A7B55A4df39A9B7B5F781ec0e53539694873#code

`slither-check-erc optim:0xaec84eac74981ab22905919cb282b78c7ca782df Market --erc erc4626 `

**Comment by smonicas** [comment]
Yes you would have to check the implementation
