### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'disable_solc_warnings'

### ISSUE THREAD

**Issue by elenadimitrova** [crytic/slither#288]
Running `slither` with the following config

```
{
  "detectors_to_exclude": "unused-state-variables,conformance-to-solidity-naming-conventions,incorrect-versions-of-solidity",
  "solc": "solc",
  "solc_args": "--allow-path .",
  "disable_solc_warnings": true
}
```

yields error
```
$ slither contracts/ --config-file slither.conf.json
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 514, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 522, in main_impl
    args = parse_args(all_detector_classes, all_printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 446, in parse_args
    if getattr(args, key) == defaults_flag_in_config[key]:
AttributeError: 'Namespace' object has no attribute 'disable_solc_warnings'
```

**Comment by elenadimitrova** [comment]
Additionally, running with the option in the command line also throws
```
$ slither contracts/ --disable-solc-warnings
slither: error: unrecognized arguments: --disable-solc-warnings
```

**Comment by montyly** [comment]
Hi @elenadimitrova,

Thank you for reporting the issue. 

The documentation on the wiki is out of date, and the flag is now `--solc-disable-warnings` / `solc_disable_warnings` (json). I will update the wiki.

The `solc_args` flag had an issue, that we fixed in [`crytic-compile`](https://github.com/crytic/crytic-compile) master branch. We are going to do a release containing the fix in a few days. In the meantime, you do not need to add `--allow-paths .`, as crytic-compile does it [by default](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/platform/solc.py#L206-L216).

**Comment by elenadimitrova** [comment]
This works when using the `--solc-disable-warnings` option in the command line but doesn't when using a config file. In fact nothing from my config file is picked up. I might open another issue for this.

**Comment by elenadimitrova** [comment]
Confirming it's fixed.
