### ISSUE TITLE
Expression not parsed IndexRangeAccess

### ISSUE THREAD

**Issue by petejkim** [crytic/slither#545]
I am getting `Expression not parsed IndexRangeAccess` error, I am assuming this is due to my use of the [array slices](https://solidity.readthedocs.io/en/v0.6.0/types.html#array-slices)?

**Comment by montyly** [comment]
Hi @petejkim, thank you for reporting this.

We will add the support for array slices soon.

**Comment by montyly** [comment]
Hi @petejkim, thank you again for reporting this.

We added a partial support in https://github.com/crytic/slither/pull/550. The fix is in master and will be available in the upcoming release. 

Note that this is a temporary fix, and we will investigate  for a long term solution (https://github.com/crytic/slither/issues/552)
